function [ chirpSymbols ] = ...
                            chirpModulation( QPSKsymbols, chirpSequence, chirpIndex )
% ----------------------------------------------------------------------- %
% ======================================================================= %
% chirpModulation  : Function Summary
% ======================================================================= %
% ----------------------------------------------------------------------- %
% The stream of DQPSK symbols shall be modulated onto the stream of 
% subchirps that is generated by the chirp-shift keying (CSK) generator. 
% The effect of the differential quadrature chirp-shift keying (DQCSK) 
% modulation shall be that each subchirp is multiplied with a DQPSK value 
% that has unit magnitude and has constant phase for the duration of the 
% subchirp
% ======================================================================= %
% Get the global variables
% ----------------------------------------------------------------------- %
samplingFreqMhz=32;  % Sampling Frequency in MHz
carrierFreqGHz=2.45; % Carrier frequency in GHz
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
% Table 26g�Equation (1a) numerical parameters�timing parameters
% timing parameters values Multiple of 1/32MHz
% Tchirp 6 us 
% Tsub 1.1875 us 
% T1 = 1468.75 us 
% T2 = 2312.5 ns 
% T3 = 4156.25 ns 
% T4 = 0 ns 
% ----------------------------------------------------------------------- %
Tchirp= 6 * samplingFreqMhz;
Tsub = 1.1875 * samplingFreqMhz;
Tau_m = [0.46875, 0.3125, 0.15625, 0]* samplingFreqMhz;
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
% 6.5a.4.2 Active usage of time gaps
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
% In conjunction with the subchirp sequence , Different pairs of time gaps 
% are defined. The time gaps are chosen to make the four sequences even 
% closer to being orthogonal. The time gaps shall be applied alternatively 
% between subsequent chirp symbols as shown  in Figure 20d. 
% The values of the time gaps are calculated from the timing parameters 
% specified in Table 26g (in 6.5a.4.3). 
Tgap(1) = Tchirp - 4*Tsub - 2*Tau_m(chirpIndex);
Tgap(2) = Tchirp - 4*Tsub + 2*Tau_m(chirpIndex);
% --------------------------------------------------
% ----------------------------------------------------------------------- %
% make sure the input is a row vector
[x y]=size(QPSKsymbols);
if x>1
   QPSKsymbols=transpose(QPSKsymbols); 
end
% ----------------------------------------------------------------------- %
numQPSKsymbols=length(QPSKsymbols);
% ----------------------------------------------------------------------- %
%Prepare a zero array for the output. This saves run time considerably
chirpSymbols=zeros(1,numQPSKsymbols/4*Tchirp);
% ----------------------------------------------------------------------- %
% ----------------------------------------------------------------------- %
% Start modulating the chirp sequence and adding gaps 
% ----------------------------------------------------------------------- %
startIndex=0;
for QPSKgroupCounter=0:numQPSKsymbols/4-1
    % ------------------------------------------------------------------- %
    % Capture 4 DQPS symbols
    % ------------------------------------------------------------------- %
    groupIndex=(4*QPSKgroupCounter+1 : 4*QPSKgroupCounter+4);
    modulationSymbols=repmat(QPSKsymbols(groupIndex), Tsub ,1);
    
    evenOdd=mod(QPSKgroupCounter,2);
    % ------------------------------------------------------------------- %
    % Modulate the 4 subchrip sequence with the 4 DQPSK symbols
    % Then, reshape and produce one sequence
    % ------------------------------------------------------------------- %
    tmp= reshape(chirpSequence .* modulationSymbols , 1, 4*Tsub);
    % ------------------------------------------------------------------- %
    % Calculate the time gap after this chirp sequence. The gap varies in
    % even and odd sequences
    chirpSymbolLength= 4*Tsub + Tgap(evenOdd+1); % equal to length(tmp)
    % ------------------------------------------------------------------- %
    % concatenate the chip sequences
    % ------------------------------------------------------------------- %
    chirpSymbols(1+startIndex: startIndex + 4*Tsub)= tmp;
                        
    startIndex=startIndex + chirpSymbolLength;
%-***********************************************************************-%
%-***********************************************************************-%
end
end



