`timescale 1ns / 1ps

module tb_CSS_Transmitter_Top;


    reg        clk;
    reg        rstn;


    reg        start_Tx;
    reg        rate;
    reg  [7:0] payloadLength;
    reg        payload_we;
    reg  [6:0] payload_addr;
    reg  [7:0] payload_din;


    wire [5:0] DAC_RE_polar,DAC_IM_polar,DAC_RE_cart,DAC_IM_cart;


    wire       system_busy;
    wire       len_err;
    wire [9:0] final_ppdu_nibbles;


    CSS_Transmitter_Top uut (
        .clk               (clk),
        .rstn              (rstn),
        .start_Tx          (start_Tx),
        .rate              (rate),
        .payloadLength     (payloadLength),
        .payload_we        (payload_we),
        .payload_addr      (payload_addr),
        .payload_din       (payload_din),


        .DAC_RE_cart       (DAC_RE_cart),
        .DAC_IM_cart       (DAC_IM_cart),
        .system_busy       (system_busy),
        .len_err           (len_err),
        .final_ppdu_nibbles(final_ppdu_nibbles)
    );


    initial begin
        clk = 0;
        forever #15.625 clk = ~clk;
    end


    initial begin
        #10_000_000;
        $display("[%0t] ERROR: Simulation Safety Timeout Reached!", $time);
        $finish;
    end


    initial begin

        rstn          = 0;
        start_Tx      = 0;
        rate          = 0;
        payloadLength = 8'd4;
        payload_we    = 0;
        payload_addr  = 7'd0;
        payload_din   = 8'd0;


        #100;
        rstn = 1;
        #62.5;

        $display("[%0t] System Reset Complete. Loading Payload RAM...", $time);


        @(negedge clk);
        payload_we = 1; payload_addr = 7'd0; payload_din = 8'hDE;
        @(negedge clk);
        payload_we = 1; payload_addr = 7'd1; payload_din = 8'hAD;
        @(negedge clk);
        payload_we = 1; payload_addr = 7'd2; payload_din = 8'hBE;
        @(negedge clk);
        payload_we = 1; payload_addr = 7'd3; payload_din = 8'hEF;

        @(negedge clk);
        payload_we = 0;

        #100;


        $display("[%0t] Triggering start_Tx...", $time);

        @(negedge clk);
        start_Tx = 1;

        @(negedge clk);
        start_Tx = 0;


        wait(system_busy == 1'b1);
        $display("[%0t] Transmission Started. system_busy is HIGH.", $time);
        $display("[%0t] NOTE: CSS Modulation takes many clock cycles. Waiting for completion...", $time);


        wait(system_busy == 1'b0);

        if (len_err) begin
            $display("[%0t] ERROR: Length Error asserted!", $time);
        end else begin
            $display("[%0t] Transmission Finished. system_busy is LOW.", $time);
            $display("[%0t] Total words generated by Framer: %0d", $time, final_ppdu_nibbles);
        end

        #500;
        $display("[%0t] Simulation Complete.", $time);
        $finish;
    end


    initial begin
        $dumpfile("css_tx_pipeline.vcd");
        $dumpvars(0, tb_CSS_Transmitter_Top);
    end

endmodule
